# Generated by Django 5.0.6 on 2024-07-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_genero_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id_genero',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
